" Vim RC

" == Start Vundle ================================================================
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Ruby, Rails, Rspec
"Plugin 'thoughtbot/vim-rspec'
Plugin 'Keithbsmiley/rspec.vim'
Plugin 'slim-template/vim-slim'
Plugin 'derekwyatt/vim-scala'
Plugin 'kchmck/vim-coffee-script'

" == End Vundle ==================================================================

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set encoding=utf-8
set number

" twig
set syntax=htmldjango

autocmd BufNewFile,BufRead *.less set filetype=css

" rspec.vim (Keithbsmiley)
autocmd BufReadPost,BufNewFile *_foo.rb set syntax=rspec

set mouse=a
set autoindent
set tabstop=2
set expandtab
set ambiwidth=double
set shiftwidth=2
set backspace=indent,eol,start

" Auto remove line last whitespaces
autocmd BufWritePre * :%s/\s\+$//ge

autocmd FileType make,c,cpp,h,hpp,hxx setlocal noexpandtab tabstop=4
autocmd FileType make,c,cpp setlocal noexpandtab tabstop=3
au BufNewFile,BufRead *.c,*.cpp,*.hpp,*.hxx set noexpandtab tabstop=3 shiftwidth=3

autocmd FileType cucumber compiler cucumber | setl makeprg=cucumber\ \"%:p\"
autocmd FileType ruby
      \ if expand('%') =~# '_test\.rb$' |
      \   compiler rubyunit | setl makeprg=testrb\ \"%:p\" |
      \ elseif expand('%') =~# '_spec\.rb$' |
      \   compiler rspec | setl makeprg=rspec\ \"%:p\" |
      \ else |
      \   compiler ruby | setl makeprg=ruby\ -wc\ \"%:p\" |
      \ endif
autocmd User Bundler
      \ if &makeprg !~# 'bundle' | setl makeprg^=bundle\ exec\  | endif

autocmd BufReadPost,BufNewFile *_spec.rb set syntax=rspec
autocmd BufReadPost,BufNewFile *.scala set syntax=scala
autocmd BufReadPost,BufNewFile *.slim set syntax=slim

" Coffee
au BufRead,BufNewFile,BufReadPre *.coffee   set filetype=coffee
autocmd FileType coffee    setlocal sw=2 sts=2 ts=2 et
autocmd BufWritePost *.coffee silent make! 
autocmd QuickFixCmdPost * nested cwindow | redraw! 
nnoremap <silent> <C-C> :CoffeeCompile vert <CR><C-w>h

" execute pathogen#infect()

syntax on
filetype plugin indent on

autocmd BufWritePre * :%s/\s\+$//ge
