" Vim RC

" == Start Vundle ================================================================
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" Ruby / Rails
Plugin 'thoughtbot/vim-rspec'
Plugin 'tpope/vim-haml'
Plugin 'Keithbsmiley/rspec.vim'
Plugin 'slim-template/vim-slim'
" Others, JS
Plugin 'derekwyatt/vim-scala'
Plugin 'kchmck/vim-coffee-script'
Plugin 'leafgarland/typescript-vim'
Plugin 'posva/vim-vue'
Plugin 'mtscout6/vim-cjsx'
Plugin 'digitaltoad/vim-pug'
Plugin 'ianks/vim-tsx'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'altercation/vim-colors-solarized'
call vundle#end()
filetype plugin indent on

" Solarized
syntax enable
set background=dark
colorscheme solarized

set encoding=utf-8
set number

" twig
set syntax=htmldjango

autocmd BufNewFile,BufRead *.less set filetype=css
autocmd BufReadPost,BufNewFile Gemfile,*.jbuilder,*.ruby set syntax=ruby
" autocmd FileType vue syntax sync fromstart
autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css

set mouse=a
set autoindent
set tabstop=2
set expandtab
set ambiwidth=double
set shiftwidth=2
set backspace=indent,eol,start

" Auto remove line last whitespaces
autocmd BufWritePre * :%s/\s\+$//ge

autocmd FileType make,c,cpp,h,hpp,hxx setlocal noexpandtab tabstop=4
autocmd FileType make,c,cpp setlocal noexpandtab tabstop=3
au BufNewFile,BufRead *.c,*.cpp,*.hpp,*.hxx set noexpandtab tabstop=3 shiftwidth=3

autocmd FileType cucumber compiler cucumber | setl makeprg=cucumber\ \"%:p\"
autocmd FileType ruby
      \ if expand('%') =~# '_test\.rb$' |
      \   compiler rubyunit | setl makeprg=testrb\ \"%:p\" |
      \ elseif expand('%') =~# '_spec\.rb$' |
      \   compiler rspec | setl makeprg=rspec\ \"%:p\" |
      \ else |
      \   compiler ruby | setl makeprg=ruby\ -wc\ \"%:p\" |
      \ endif
autocmd User Bundler
      \ if &makeprg !~# 'bundle' | setl makeprg^=bundle\ exec\  | endif

autocmd BufReadPost,BufNewFile *_spec.rb set syntax=rspec
autocmd BufReadPost,BufNewFile *.dia set syntax=ruby
autocmd BufReadPost,BufNewFile *.scala set syntax=scala
autocmd BufReadPost,BufNewFile *.slim set syntax=slim
autocmd BufRead,BufNewFile *.slim setfiletype slim

" Coffee
au BufRead,BufNewFile,BufReadPre *.coffee   set filetype=coffee
autocmd FileType coffee    setlocal sw=2 sts=2 ts=2 et
" autocmd BufWritePost *.coffee silent make!
autocmd QuickFixCmdPost * nested cwindow | redraw!
nnoremap <silent> <C-C> :CoffeeCompile vert <CR><C-w>h

" execute pathogen#infect()

syntax on
filetype plugin indent on

autocmd BufWritePre * :%s/\s\+$//ge
nmap j <up>
nmap k <down>

set ambiwidth=single
